name: smart_tender
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  lucide_icons: ^0.257.0
  fl_chart: ^1.1.1
  provider: ^6.1.5+1
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  share_plus: ^12.0.1
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
